// get all category
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

// get list category
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS";
export const GET_LIST_CATEGORY_REQUEST = "GET_LIST_CATEGORY_REQUEST";
export const GET_LIST_CATEGORY_FAIL = "GET_LIST_CATEGORY_FAIL";
// get one category
export const GET_ONE_CATEGORY_SUCCESS = "GET_ONE_CATEGORY_SUCCESS";
export const GET_ONE_CATEGORY_REQUEST = "GET_ONE_CATEGORY_REQUEST";
export const GET_ONE_CATEGORY_FAIL = "GET_ONE_CATEGORY_FAIL";
// pagination
export const SET_PAGE = "SET_PAGE";
export const LIMIT_PAGE = "LIMIT_PAGE";
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
