// get all indgredients
export const GET_LIST_INGREDIENT_SUCCESS = "GET_LIST_INGREDIENT_SUCCESS";
export const GET_LIST_INGREDIENT_REQUEST = "GET_LIST_INGREDIENT_REQUEST";
export const GET_LIST_INGREDIENT_FAIL = "GET_ALL_CATEGORY_FAIL";
